#!/bin/bash
# Local Props
SDK_PATH=/home/amit/Android/Sdk
NDK_VERSION=21.3.6528147
CMAKE_VERSION=3.10.2.4988404

# Vars
NDK=$SDK_PATH/ndk/$NDK_VERSION
ROOT_DIR=$(pwd)
ABI=armeabi-v7a
MIN_SDK_VERSION=23
OUT_DIR=$ROOT_DIR/$ABI
BUILD_DIR=$ROOT_DIR/build


rm -rf $BUILD_DIR

mkdir $BUILD_DIR

cd $BUILD_DIR
# cmake ../
# make

# cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_NDK=$NDK -DANDROID_PLATFORM=android-$MIN_SDK_VERSION -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a" $ROOT_DIR 
# cmake --build 

cmake -H../ -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=$ABI -DANDROID_NDK=$NDK -DANDROID_PLATFORM=android-$MIN_SDK_VERSION -DCMAKE_ANDROID_ARCH_ABI=$ABI -DCMAKE_ANDROID_NDK=$NDK -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$ABI -DCMAKE_MAKE_PROGRAM=$SDK_PATH/cmake/$CMAKE_VERSION/bin/ninja -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=$MIN_SDK_VERSION -B$BUILD_DIR -GNinja
ninja

# ./firstDemo
